### ISSUE TITLE
Handle postgres user passwords using pfile securely

### ISSUE THREAD

**Issue by salmanahmed-postgresql** [stormatics/pg_cirrus#19]
pfile needs to be handled securely

**Comment by salmanahmed-postgresql** [comment]
As per the R&D effort the password and pfile can be handled securely using either or both of the following options:

- Create a directory using a random number, change its permission to 600, save pfile in it use the pfile for initdb command and creating replication user and delete it.

-  Use a jump host to trigger pg_cirrus

**Comment by salmanahmed-postgresql** [comment]
Will be further discussed and implemented when the restructuring of pg_cirrus using Ansible and Python is complete.

**Comment by Semab-Tariq** [comment]
There are different steps that we can follow 
1 - Use getpass from python to take the password
2 - Use Ansible Vault to secure the password

**Comment by DevBotX** [comment]
We can use following steps to secure this password
1 - use getpass from python to take user input 
2 - use Ansible vault to secure the password

**Comment by salmanahmed-postgresql** [comment]
We are using ansible vault to store PostgreSQL server password.
It is a pre requirement for user to create a vault.yml file before executing pg_cirrus
A hidden pfile is created on home of user on primary server with permission set to 0600
The password from vault.yml is saved to this .pfile
User is asked for vault password when pg_cirrus is triggered.

**Comment by salmanahmed-postgresql** [comment]
Instead of asking user for vault password, a file with permissions 0600 containing vault password must be created as a prerequisite. The path of this file is requested from user and file is passed automatically when running playbooks.

A .pgpass file with permissions 0600 containing pfile_password value from vault.yml will be created on standby servers.
