### ISSUE TITLE
Create a release announcement for Beta 1

### ISSUE THREAD

**Issue by umairshahid** [stormatics/pg_cirrus#41]
Use the existing text that we had created for announcing the Alpha release and modify it to announce the Beta release. This text will be designed to go out on the pgsql-announce mailing list.

**Comment by salmanahmed-postgresql** [comment]
This is the link to the release announcement document

https://docs.google.com/document/d/1I8rzoD3qKB7oFI5tGEdskMJwuVW6aSV7Pl_3WofIbU0/

**Comment by salmanahmed-postgresql** [comment]
Release announcement has been created and approved, it will be sent out to psql-announce
