### ISSUE TITLE
Stop duplication of connection details of standby server 2 in pgpool.conf

### ISSUE THREAD

**Issue by salmanahmed-postgresql** [stormatics/pg_cirrus#54]
If pgpool's playbook is triggered again then in /etc/pgpool2/pgpool.conf following values for following parameters get duplicated at EOF.

backend_hostname2 
backend_port2 
backend_weight2 
backend_data_directory2

**Comment by salmanahmed-postgresql** [comment]
This issue has been fixed, pull request generated.

**Comment by salmanahmed-postgresql** [comment]
This issue has been fixed, pull request is under review.

**Comment by DevBotX** [comment]
PR merged closing the issue
