### ISSUE TITLE
Add Exception Handling for User-Provided PostgreSQL Version Number

### ISSUE THREAD

**Issue by salmanahmed-postgresql** [stormatics/pg_cirrus#74]
As of now any input entered when prompted for PG_VERSION is taken as input and saved inside conf.yml file. Exception handling needs to be added so that following requirements are met before saving PG_VERSION to conf.yml file.

- [x] PG_VERSION value should be numeric only
- [x] PG_VERSION value should be a supported PostgreSQL version for pg_cirrus
- [x] PG_VERSION value should be lesser than or equal to latest available PostgreSQL version
- [x] In case of wrong entries user must be asked again for version, but after 3 wrong entries pg_cirrus shall exit

**Comment by salmanahmed-postgresql** [comment]
Exception handling has been added for User-Provided PostgreSQL version number. Here is the output of invalid entries.

Getting latest PostgreSQL stable version ...
Enter PostgreSQL version (Latest: 15): 12
Invalid input: Version cannot be lesser than minimum supported version 13.
Enter PostgreSQL version (Latest: 15): 89
Invalid input: Version cannot be greater than latest available version 15.
Enter PostgreSQL version (Latest: 15): lkj
Invalid input: Version should be a number.
Too many invalid inputs. Exiting the pg_cirrus.

**Comment by salmanahmed-postgresql** [comment]
Logic for PG_VERSION value to be only two digit not added as it is unnecessary when PG_VERSION value must be greater than or equal to minimum supported version and lesser than equal to latest available version

**Comment by salmanahmed-postgresql** [comment]
This issue has been resolved. Pull request #82 has been generated against this issue. Changes will be merged after PR has been reviewed.

**Comment by DevBotX** [comment]
Pull Request si merged ...
